# GitBash
alias vi='vim'
alias trev='cd /c/Users/trevo'
alias doc='cd /c/Users/trevo/Documents'
alias dwn='cd /c/Users/trevo/Downloads'
alias desk='cd /c/Users/trevo/Desktop'
alias pic='cd /c/Users/trevo/Pictures'
alias vid='cd /c/Users/trevo/Videos'
alias dev='cd /d/dev'
alias blu='cd /c/Users/trevo/Documents/Bluetooth'
alias mis='cd /c/Users/trevo/mis'

# WSL
alias trev='cd /mnt/c/Users/trevo'
alias doc='cd /mnt/c/Users/trevo/Documents'
alias dwn='cd /mnt/c/Users/trevo/Downloads'
alias desk='cd /mnt/c/Users/trevo/Desktop'
alias pic='cd /mnt/c/Users/trevo/Pictures'
alias vid='cd /mnt/c/Users/trevo/Videos'
alias dev='cd /mnt/d/dev'
alias blu='cd /mnt/c/Users/trevo/Documents/Bluetooth'
alias mis='cd /mnt/c/Users/trevo/mis'

alias p3='python3'
alias s='source'
alias h='heroku'
alias venv='virtualenv'
alias act='s ./bin/activate'
alias dact='deactivate'
alias hl='h local'
alias f='foreman'
alias fs='foreman start'
alias vl='vim ~/localinfo'

# some more ls aliases
alias ll='ls -alF'
alias l='ls -CF'
alias la='ls -A'
alias l1='ls -lr1a'
alias p='python3'
alias act='source ./venv/Scripts/activate'
alias t='/bin/terraform.exe'
alias k='C:/Program\ Files/Docker/Docker/resources/bin/kubectl.exe'
alias d='C:/Program\ Files/Docker/Docker/resources/bin/docker'
alias ex='explorer.exe'
